### ISSUE TITLE
Chart memoization might have a memory leak?

### ISSUE THREAD

**Issue by dancoates** [bigdatr/pnut#36]
Not sure about this but just leaving this here as a reminder to check it out. The memoization cache in chart is created in the constructor and isn't cleared which might mean that the memos object grows very large over time.

**Comment by dxinteractive** [comment]
Hmm, most things only memoize on columns, so each method would memoize (column arg combinations) * (rows) at most. I think it makes sense to leave clearing to the garbage collector, as trying to judge a time to do it earlier than that could be tricky.

**Comment by dancoates** [comment]
Looks like the memoize stuff in Chart.jsx isn't actually used - but the boilerplate stuff that is there will need to be updated to avoid this problem when it is used so I'll leave this open for the moment.
